### PR TITLE
ADD support for push notifications

### PR DESCRIPTION
**Pull request by rogiervandenberg**
I wanted to be able to send push messages for intercom replies and also have the possibility to send push notifications myself (using FCM). So I added that. 👍

### CODE REVIEW

**Comment by MrAlek** [comment]
Great add! We should do this for iOS too, I could add in on that as I was going to implement it myself anyway.

**Comment by Zazo032** [comment]
@v3rm0n can you check why Codemagic is failing?

**Comment by v3rm0n** [comment]
Looks like an issue with Codemagic itself

**Comment by MrAlek** [comment]
@v3rm0n could you cut a new version to Dart Pub?

**Comment by spiritinlife** [comment]
If notification is not coming from Intercom but from another service, eg directly from fcm, will this allow for the notification to be handled by the firebase_messaging library?

My initial tests show that is not handled but i may have misconfigured something 🤷‍♂

**Comment by Zazo032** [comment]
Are you testing it on Android or iOS? If something isn't working properly, as this PR is merged, it is better to file a new issue.

**Comment by spiritinlife** [comment]
I am testing on Android ( ios is not implemented ), will look further into it.

**Pull request merged**
