### PR TITLE
Add possibility to register for Intercom push notifications on iOS - fresh with master

### PR DESCRIPTION
**Pull request by pawlowskim**
This is just merge with master and bumped version of this PR https://github.com/v3rm0n/intercom_flutter/pull/60
I don't want to do it on my local master since we are using it ATM, we need to switch to other branch and test changes that's why I have created new branch for this PR.

### CODE REVIEW

**Review by v3rm0n — APPROVED** [review]

**Comment by Isakdl** [comment]
@pawlowskim the functions handlePush handlePushMessage and isIntercomPush are not implemented for ios in this version, right? How much work would it be to implement? My Objective-C knowledge is very limited, but by the looks of it in the android code, it is just a call to the native Intercom lib.

**Comment by pawlowskim** [comment]
They are not. Probably you are right, and it's only porting to native API calls.

**Comment by Isakdl** [comment]
Are you willing to take a look at that? I could try but it would probably be best if this was merged first in that case.

Also I have tested this updated with flutter 1.17.2, 1.17.3 and 1.17.4, There seems to be some bug with flutter 1.17.3 and this package (the pushnotifications stopped working), but since it does work in 1.17.4 I assume the issue is in the flutter lib.

**Comment by pawlowskim** [comment]
@Isakdl Unfortunately no. I'm working on changes when we need it for our commercial projects. If something might help for community, I'm making a PR. I'm too busy :/

**Comment by ghost** [comment]
This version is working and sending push notifications but #60 did not work

**Comment by j0nscalet** [comment]
@v3rm0n since @pawlowskim was kind enough to resolve the conflicts from #60 here, would you be able to merge this?Seems like @pawlowskim himself and @kristianeaw have been using it in production for several months now.

**Comment by chillbrodev** [comment]
@v3rm0n @pawlowskim - This issue recently caused severe headache with implementing iOS Push support via Intercom. We worked around it by calling Intercom directly in the AppDelegate.swift file. This should be merged in and deployed ASAP as I am sure there are other users struggling with iOS Push. Intercom is an important tool for mobile apps and since this is the unofficial/official SDK, this support is paramount.

**Comment by deepak786** [comment]
could you please test the updated/latest intercom_flutter by overriding the library in pubspec.yml under `dependency_overrides`:

```
intercom_flutter:
    git:
      url: https://github.com/v3rm0n/intercom_flutter
      path: intercom_flutter
```

Follow this thread https://github.com/v3rm0n/intercom_flutter/issues/149 for how to use the method `sendTokenToIntercom`

**Comment by pawlowskim** [comment]
I just tested `intercom_flutter: 4.0.0` and it seems to work. I'm closing PR because of that.

**Pull request closed without merging**
