### PR TITLE
Unread messages count listener

### LINKED ISSUE #43: Does this support listening to unread conversation count?
Is there a way to listen to incoming messages/ unread conversation count ?
Suppose you want to listen to the count and update the screen whenever the count changes,

Intercom has this listener for Android:
`Intercom.client().addUnreadConversationCountListener(listener);`

and this for iOS
```
[[NSNotificationCenter defaultCenter] addObserver:self
     selector:@selector(updateUnreadCount:)
         name:IntercomUnreadConversationCountDidChangeNotification
       object:nil];
```

Is this implemented?

### PR DESCRIPTION
**Pull request by marinat**
https://github.com/v3rm0n/intercom_flutter/issues/43 attempted implementation

### CODE REVIEW

**Review by Zazo032 — COMMENTED** [review]
Hi @marinat! Thanks for filling this, overall LGTM, could you add some test similar to the existing ones? I don't have an active Intercom account so I can't verify it works. Also, could you bump the version number in `pubspec.yaml` (2.2.0 seems fine) and add your changes to `CHANGELOG.md`?

**Comment by marinat** [comment]
I don't know how to write test, I used EventChannel, that not have MockMethodCallHandler like MethodChannel. Also I  wrote very simple method in intercom dart file:
<pre><code>static Stream<dynamic> getUnreadStream() 
  {
    return _unreadChannel.receiveBroadcastStream();
  }</code></pre>

**Comment by marinat** [comment]
Or who can help me to write correct tests?

**Review by Zazo032 — APPROVED** [review]
LGTM. I'm not really sure on how to test this, so I'll merge it and wait for feedback if something isn't working properly.

**Comment by Spikes042** [comment]
I can test with a live API key if you want? Before you publish to pub.dev
And I mean, just a basic functionality test

**Comment by Spikes042** [comment]
This might also help for writing tests: https://github.com/flutter/plugins/blob/master/packages/battery/test/battery_test.dart

**Comment by Zazo032** [comment]
The code seems ok, but it would be great if you could provide live feedback about this

**Comment by marinat** [comment]
@Spikes042 many thanks for tests! :)

**Pull request merged**
