### PR TITLE
Add logEvent method

### PR DESCRIPTION
**Pull request by MrAlek**

### CODE REVIEW

**Comment by Zazo032** [comment]
Thanks @MrAlek for this implementation. Could you add a test to ensure this is working properly?

**Comment by MrAlek** [comment]
@Zazo032 Done :)

**Comment by Zazo032** [comment]
Thanks! Maybe @v3rm0n is a bit busy to merge but it'll be a really good addition.

**Comment by v3rm0n** [comment]
Released as `2.0.2`

**Comment by MrAlek** [comment]
Awesome! 🙌

**Pull request merged**
