### PR TITLE
add displayMessageComposer method

### PR DESCRIPTION
**Pull request by knaeckeKami**
add a "displayMessageComposer", which opens the message composer with an optional initial message

### CODE REVIEW

**Comment by Zazo032** [comment]
Great! Thanks for your contribution. Could you add some test so this functionality is not regressed with future changes?

**Comment by knaeckeKami** [comment]
Of course. Is this test enough?

**Review by Zazo032 — APPROVED** [review]
LGTM

**Comment by knaeckeKami** [comment]
Oh, yeah I added another Bugfix and didn't think about that the commit would be added to this PR
There was a typo in the kotlin method name that I fixed

**Pull request merged**
