### PR TITLE
#100 Fix UninitializedPropertyAccessException on Android

### LINKED ISSUE #100: Intercom error when pressing the back button. Shutting down VM
DecorView@15ef58e[MainActivity]
D/AndroidRuntime( 8635): Shutting down VM
E/AndroidRuntime( 8635): FATAL EXCEPTION: main
E/AndroidRuntime( 8635): Process: com.android.app, PID: 8635
E/AndroidRuntime( 8635): java.lang.RuntimeException: Unable to destroy activity {com.android.app/com.android.app.MainActivity}: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4589)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4611)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:39)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime( 8635): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1861)
E/AndroidRuntime( 8635): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 8635): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.main(ActivityThread.java:6819)
E/AndroidRuntime( 8635): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8635): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime( 8635): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)
E/AndroidRuntime( 8635): Caused by: kotlin.UninitializedPropertyAccessException: lateinit property unreadConversationCountListener has not been initialized
E/AndroidRuntime( 8635): 	at io.maido.intercom.IntercomFlutterPlugin.onDetachedFromEngine(IntercomFlutterPlugin.kt:209)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:262)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.remove(FlutterEngineConnectionRegistry.java:270)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.removeAll(FlutterEngineConnectionRegistry.java:278)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.destroy(FlutterEngineConnectionRegistry.java:122)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:365)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:555)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivity.release(FlutterActivity.java:589)
E/AndroidRuntime( 8635): 	at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:610)
E/AndroidRuntime( 8635): 	at android.app.Activity.performDestroy(Activity.java:7395)
E/AndroidRuntime( 8635): 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
E/AndroidRuntime( 8635): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4574)
E/AndroidRuntime( 8635): 	... 11 more
Lost connection to device.
Exited (sigterm)

### PR DESCRIPTION
**Pull request by jonyas**
Fixes #100

### CODE REVIEW

**Comment by JEuler** [comment]
Hi! Any luck with merging this?

**Comment by jonyas** [comment]
@JEuler it needs an approval from project owner. I guess @Zazo032 ?

**Comment by JEuler** [comment]
Yeah, of course I understand!

**Comment by Zazo032** [comment]
Hi @jonyas, do you know if this is only Android-specific or can happen also in ios?

**Comment by jonyas** [comment]
@Zazo032 it is only Android specific. We didn't notice any iOS weird behaviours when starting and closing apps on iOS.

**Review by Zazo032 — APPROVED** [review]
LGTM, thanks!

**Comment by jonyas** [comment]
I think someone with write permissions need to merge it. Besides that, for some reason, codemagic build did not trigger. Any ideas?

**Comment by Zazo032** [comment]
Seems like Codemagic is down or something isn't triggering the build, @v3rm0n could you check?

**Comment by v3rm0n** [comment]
Looks like CodeMagic has changed their billing and it doesn't work anymore without billing details. I added mine temporarily to see how costly it will be so maybe we need to look for alternatives. If this branch is rebased it should trigger again.

**Comment by jonyas** [comment]
It seems it didn't trigger :D

**Comment by Zazo032** [comment]
@v3rm0n I contacted Codemagic and they told me this:

> Hey - we cancelled your current subscription and moved your team back to a free plan, so hopefully everything should function as normal now.

@jonyas try to push an empty commit to see if that triggers the build now

**Comment by jonyas** [comment]
Done, not much luck yet (I renamed my previous commit message).

**Comment by v3rm0n** [comment]
I can see that the webhook was triggered and we got success back from CodeMagic, but no build has been triggered...
Also there is no possibility to manually trigger a build for PR's.

**Comment by v3rm0n** [comment]
I removed CodeMagic and added Github Actions instead. Please try to rebase again.

**Comment by VeArnold** [comment]
Not sure on your set-up, but it does not look like triggering is enabled in the current codemagic.yaml file.

**Comment by v3rm0n** [comment]
@VeArnold looks like you are right. IMO not a good default for CI configuration: not actually running :man_facepalming:

**Comment by jonyas** [comment]
Now it's working in github actions :octocat: !

**Review by v3rm0n — APPROVED** [review]

**Comment by v3rm0n** [comment]
Published 2.3.2

**Comment by jonyas** [comment]
Great, thanks a lot!

**Comment by JEuler** [comment]
Thanks!

**Pull request merged**
