### PR TITLE
intercom_flutter_platform_interface

### PR DESCRIPTION
**Pull request by deepak786**
The first PR for the separated intercom_flutter_platform_interface.

### CODE REVIEW

**Comment by Zazo032** [comment]
Platform interface is the same one found in #111 right? If so, this can be merged but @v3rm0n will have to push it to pub.dev

**Comment by deepak786** [comment]
@Zazo032 yes, its the same from https://github.com/v3rm0n/intercom_flutter/pull/111

**Review by Zazo032 — APPROVED** [review]
LGTM modulo publishing to pub.dev from @v3rm0n

**Comment by deepak786** [comment]
@Zazo032 I can push this package from my pub account if you want.

**Pull request merged**
