### PR TITLE
Adds documentation for using --dart-define variables to initialize th…

### PR DESCRIPTION
**Pull request by sirTomasson**
Adds documentation for using `--dart-define` variables to initialise the IntercomFlutterPlugin SDK on Android.

This is a solution we used in our app to avoid hardcoding Intercom tokens. We believe it could be helpful to others trying to solve the same problem.

Cheers!

### CODE REVIEW

**Comment by deepak786** [comment]
Nice!!!

Then we can also use the Environment variables on the dart side to initialize the SDK.

```
String appId = String.fromEnvironment("APP_ID", "");
String androidKey = String.fromEnvironment("ANDROID_TOKEN", "");
String iOSKey = String.fromEnvironment("IOS_TOKEN", "");

```

**Comment by deepak786** [comment]
@sirTomasson I'm thinking that it would be better if we add a separate section for this documentation instead of adding it under the "Android" section. And also with how to use tokens from --dart-defines on the dart side.

It can be at the end of the readme file with title "Using of intercom keys with --dart-define"

What do you think?

**Comment by sirTomasson** [comment]
> @sirTomasson I'm thinking that it would be better if we add a separate section for this documentation instead of adding it under the "Android" section. And also with how to use tokens from --dart-defines on the dart side.
> 
> It can be at the end of the readme file with title "Using of intercom keys with --dart-define"
> 
> What do you think?

I agree. I have moved my docs to a separate section at the bottom, and added an example usage of --dart-define. 
Let me know how you like these changes.

**Comment by deepak786** [comment]
@sirTomasson I have no access to edit your PR so I created a new PR for the same https://github.com/v3rm0n/intercom_flutter/pull/322

Let me know if you have any suggestions.

**Comment by deepak786** [comment]
@sirTomasson Thanks for this PR and Solution. 
Closing this PR because of https://github.com/v3rm0n/intercom_flutter/pull/322

**Pull request closed without merging**
