### PR TITLE
#68 Updated AndroidManifest.xml to resolve merging error with Flutter apps with minSdk less than version 21.

### PR DESCRIPTION
**Pull request by Lekky71**
Fix for #68 .

### CODE REVIEW

**Comment by Zazo032** [comment]
Hi @Lekky71, thanks for the contribution. Could you give some context on when does this error happen?

**Comment by Lekky71** [comment]
> Hi @Lekky71, thanks for the contribution. Could you give some context on when does this error happen?

Sure @Zazo032 , the error happens when I include this plugin in a Flutter app that has the Android minimumSdk to be less than 21(which is the one for this plugin). This leads to conflicts when Gradle tries to merge the manifests.

The fix is to add: `<uses-sdk android:minSdkVersion="21"
          tools:overrideLibrary="io.intercom.android, io.maido.intercom, io.intercom.android.sdk.fcm, io.intercom.android.sdk"/>` to my project's AndroidManifest.xml file and also for the plugin's AndroidManifest.xml file to have  the `xmlns:tools="http://schemas.android.com/tools"` and `<uses-sdk android:minSdkVersion="21" />`.

**Comment by Zazo032** [comment]
And what will happen if you try to use this plugin on a device with an Android API version lower than 21? Intercom SDK doesn't support those versions (just curious).

**Comment by Lekky71** [comment]
> And what will happen if you try to use this plugin on a device with an Android API version lower than 21? Intercom SDK doesn't support those versions (just curious).

I put this check in my app this, reason is because I would still like to support <21 on my app, the only compromise is that they would not be able to use Intercom, I run this check before calling any Intercom function. 

`static Future<bool> checkIfCanRunIntercom() async {
    if (Platform.isAndroid) {
      var androidInfo = await DeviceInfoPlugin().androidInfo;
      var sdkInt = androidInfo.version.sdkInt;
      return sdkInt >= 21;
    }
    return true;
  }`

**Comment by Lekky71** [comment]
@Zazo032, I need an approval in order to merge.

**Comment by Zazo032** [comment]
I see, do you know if something similar may happen on iOS? Also, which would be the result if a user tries to open Intercom on a pre-21 device?

**Comment by Lekky71** [comment]
> I see, do you know if something similar may happen on iOS? Also, which would be the result if a user tries to open Intercom on a pre-21 device?

I don't think so...trying to run on pre-21 device will definitely give a runtime error at some point hence the validation on my end.

**Comment by Lekky71** [comment]
@Zazo032 Friendly reminder that I need an approval.

**Comment by Zazo032** [comment]
Could you please add a comment on `README.md` to inform that Intercom's SDK is only compatible with Android API 21+ and iOS 10+? If users will be able to import this library on pre-21 devices, this can lead to unexpected errors that we haven't documented anywhere.

**Comment by Spikes042** [comment]
Will this compile on iOS < 10?
Because if it fails on app build then the checks won't be enough

**Comment by Zazo032** [comment]
> Will this compile on iOS < 10?
> Because if it fails on app build then the checks won't be enough

As per https://github.com/v3rm0n/intercom_flutter/blob/master/ios/intercom_flutter.podspec#L21, I guess it will fail compiling in iOS < 10

**Comment by Spikes042** [comment]
So do we want to follow Intercom's version support (this is a wrapper after all) or do we want to have users calling ```checkIfCanRunIntercom()``` before every Intercom command?

We can, of course, have this internal but that will require a dependency on device_info plugin

**Comment by Zazo032** [comment]
I don't think adding a dependency on `device_info` will be a good approach here. What do you think @v3rm0n?

**Comment by deepak786** [comment]
@Zazo032 I don't think, we should implement this. But the developer can add this check by himself/herself in his/her app.

**Comment by Zazo032** [comment]
I think adding `<uses-sdk tools:overrideLibrary="io.maido.intercom"/>` to your `AndroidManifest.xml` may also fix this. Can you try it? If you call the plugin in SDK < 21, you'll most likely get a `MissingPluginException`.

**Comment by deepak786** [comment]
Need to add the following to use the intercom on Android API < 21.
```
<!-- Intercom SDK supports min SDK 21 -->
<uses-sdk tools:overrideLibrary="io.maido.intercom, io.intercom.android, io.intercom.android.sdk.fcm, io.intercom.android.sdk, com.intercom.input.gallery, com.intercom.composer" />
```

The app will compile but there will be runtime exception as Intercom works on API >= 21.
So you have to add the check inside your app.

You can open the email composer for e.g. if the API version is < 21 else open the Intercom.

**Pull request closed without merging**
