### PR TITLE
Bump Intercom version to 6.x

### LINKED ISSUE #53: Upgrade to version 6 of intercom SDK
I received email from intercom team.

> To continue to provide all Intercom users with a fast and secure mobile experience, we are deprecating version 5 and below of the Intercom mobile SDKs. Starting June 30th 2020, version 5 and below of the iOS and Android SDKs will no longer be supported, and will no longer work on your site. To continue to use Intercom in your apps, please upgrade to version 6 of the mobile SDKs. Version 6 supports Android API level 21 and iOS 10 and above. 

Will this package update the intercom SDK?

- https://github.com/v3rm0n/intercom_flutter/blob/master/ios/intercom_flutter.podspec#L20
- https://github.com/v3rm0n/intercom_flutter/blob/master/android/build.gradle#L44

### PR DESCRIPTION
**Pull request by marbarroso**
Upgraded the Intercom version because I needed it for my project and I think it could be useful to other people too ;)

Fixes #53

### CODE REVIEW

**Review by Zazo032 — CHANGES_REQUESTED** [review]
There are some minor changes missing, could you give me write access to your fork so I can push them? https://github.com/marbarroso/intercom_flutter

**Comment by Zazo032** [comment]
@marbarroso is there any chance you could take a look soon to this PR? If you can't, I can merge it as is, and add my changes in another PR.

**Comment by marbarroso** [comment]
yes, for sure! I'll give you write access now. Sorry for the late reply, I was on holidays!

**Review by Zazo032 — APPROVED** [review]
LGTM

**Comment by Zazo032** [comment]
Thanks @marbarroso!

**Pull request merged**
