### PR TITLE
Fix incremental installation error

### PR DESCRIPTION
**Pull request by masashi-sutou**
Flutter is planing to enable incremental installation( flutter/flutter#46198 ), but this package triggers build error currently. I fixed it like this (https://github.com/tekartik/sqflite/pull/377).

If this lines are added to example/ios/Podfile,

```ruby
# Prevent Cocoapods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods',
    disable_input_output_paths: true,
    generate_multiple_pod_projects: true, # This
    incremental_installation: true # and this

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

The error will occurs:

```
Xcode's output:
↳
    /Users/masashi-sutou/workspace/flutter/intercom_flutter/ios/Classes/IntercomFlutterPlugin.m:2:9: fatal error: 'Intercom.h' file not found
    #import "Intercom.h"
            ^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

This pull request fixes this issue.

I've confirmed that the error was fixed at my projects by adding this to pubspec.yaml.

```yml
dependency_overrides:
  intercom_flutter:
    git:
      url: https://github.com/masashi-sutou/intercom_flutter.git
      ref: fix-incremental-installation-error
```

### CODE REVIEW

**Review by Zazo032 — APPROVED** [review]
LGTM. Thanks!

**Comment by Zazo032** [comment]
To upload it directly, could you bump the version in `pubspec.yaml` and add the changes to `README.md`? That way, I can publish it faster to pub.dev

**Comment by masashi-sutou** [comment]
@Zazo032  update version and  changelog 5f488e5.

**Comment by Zazo032** [comment]
Thanks!

**Pull request merged**
