### PR TITLE
Implementation of the displayMessages method

### PR DESCRIPTION
**Pull request by utopicnarwhal**
Implementation of the method `displayMessagesSpace` that shows the messages space according to Intercom docs for
iOS: https://developers.intercom.com/installing-intercom/docs/using#spaces
Android: https://developers.intercom.com/installing-intercom/docs/using-intercom-android#present-intercom-spaces

### CODE REVIEW

**Review by deepak786 — COMMENTED** [review]
LGTM.

But I suggest:
- Use `displayMessages` instead of `displayMessagesSpace`.
- Web JS has an implementation of displayMessages. https://developers.intercom.com/installing-intercom/docs/intercom-javascript#intercomshowmessages So need to implement that as well.

**Comment by utopicnarwhal** [comment]
@deepak786 The suggestions have been applied 👍

**Review by Zazo032 — APPROVED** [review]
Changes LGTM, thanks for also adding the web implementation!

**Review by deepak786 — APPROVED** [review]
@utopicnarwhal Thank you for your contribution.

**Comment by deepak786** [comment]
@utopicnarwhal can you make sure this checkbox is checked as I need to add some changes to this PR?
Screen Shot 2023-01-29 at 11 36 11 PM

**Comment by deepak786** [comment]
@utopicnarwhal 
or just do the following:

- intercom_flutter_platform_interface:
    - Bump version to 1.2.2
    - Update changelog
    
- intercom_flutter_web:
    - Bump version to 0.2.2
    - Update `intercom_flutter_platform_interface: ^1.2.2` dependency
    - Update chanelog
    
- intercom_flutter:
   - Bump version to 7.6.3
   - Update `intercom_flutter_platform_interface: ^1.2.2` dependency
   - Update  `intercom_flutter_web: ^0.2.2` dependency
   - Update changelog 
   
   
Changelog:
    - Added method `displayMessages`.
    
I'm not able to push the changes to this PR.

```
git push freska-fi HEAD:master
remote: Permission to freska-fi/intercom_flutter.git denied to deepak786.
fatal: unable to access 'https://github.com/freska-fi/intercom_flutter/': The requested URL returned error: 403
```

**Comment by utopicnarwhal** [comment]
> @utopicnarwhal can you make sure this checkbox is checked as I need to add some changes to this PR? Screen Shot 2023-01-29 at 11 36 11 PM

Unfortunately, I've created the fork from the organisation account and it doesn't have this feature (source: https://github.com/community/community/discussions/5634#discussioncomment-2968070)
I'll make the changes in the PR as you mentioned above 👍

**Comment by utopicnarwhal** [comment]
@deepak786 done

**Pull request merged**
