### PR TITLE
Implement `displayConversation`

### PR DESCRIPTION
**Pull request by theVinesh**
- Bumps Android and iOS sdks to latest
- Implement `displayConversation` to allow conversations to be presented programatically

### CODE REVIEW

**Review by deepak786 — CHANGES_REQUESTED** [review]
LGTM.

Could you please update the sdk version in the readme file as well https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/README.md#intercom_flutter

```
- Uses Intercom Android SDK Version 15.1.6
- Uses Intercom iOS SDK Version 15.1.4
```

**Comment by theVinesh** [comment]
> LGTM.
> 
> Could you please update the sdk version in the readme file as well https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/README.md#intercom_flutter
> 
> ```
> - Uses Intercom Android SDK Version 15.1.6
> - Uses Intercom iOS SDK Version 15.1.4
> ```

This is done @deepak786

**Review by deepak786 — APPROVED** [review]

**Review by Zazo032 — APPROVED** [review]

**Comment by Br1an-Boyle** [comment]
@Zazo032 @deepak786 👋🏻 
Do you guys have a Twitter account I could DM you on? Would love to chat!

**Comment by deepak786** [comment]
@Br1an-Boyle No.

**Pull request merged**
