### PR TITLE
Updated Intercom iOS SDK Version 16.0.0

### PR DESCRIPTION
**Pull request by Br1an-Boyle**
- Update to Intercom iOS SDK 16.0.0
- Removed deprecated `register` functions.

### CODE REVIEW

**Comment by Zazo032** [comment]
Thanks @Br1an-Boyle! Looks like Xcode 15 is now required. Could you add that change also to the changelog?

**Comment by deepak786** [comment]
It seems that native SDK version 16.0.0 is reverted.

**Comment by Br1an-Boyle** [comment]
Yep we reverted it. We found an issue.
A new release will be out tomorrow morning

**Comment by Br1an-Boyle** [comment]
@Zazo032 Changelog updated. 
@deepak786 iOS SDK 16.0.0 is now released.

**Comment by deepak786** [comment]
First, we will release the version with Android SDK 15.2.2 and iOS 15.2.3 
https://github.com/v3rm0n/intercom_flutter/pull/356

After that, we will update with v16

**Comment by Br1an-Boyle** [comment]
@deepak786 I've updated this PR after yesterday's release.
I've also removed some deprecated methods that we have also removed in the main Intercom SDKs.

**Review by deepak786 — APPROVED** [review]

**Pull request merged**
