### PR TITLE
Hotfix/ios register identified user

### LINKED ISSUE #13: Register with UserId doesn't work
I do this:

`final userId = utf8.encode('MY_ID');
final secret = utf8.encode('MY_SECRET');

 final hmacSha256 = Hmac(sha256, secret);
 final hash = hmacSha256.convert(userId);

 await Intercom.setUserHash('$hash');`
    
if I call: await Intercom.registerIdentifiedUser(); //Error provide userId or mail
if I call: await Intercom.registerIdentifiedUser(userID: 'MY_ID'); //Error mail can't be empty
if I call: await Intercom.registerIdentifiedUser(userID: 'MY_ID', email: 'MY_MAIL'); //Error can't use both

What is going wrong here?

### PR DESCRIPTION
**Pull request by Spikes042**
Fixes #13 #14

### CODE REVIEW

**Comment by zanuka** [comment]
@Spikes042 I've tested your hotfix out on my fork and am still getting the following error when running `Intercom.registerIdentifiedUserWithUserId`

```
[Intercom] ERROR - 'email' parameter must be an NSString and can't be nil or empty
```

**Comment by zanuka** [comment]
I tested this hotfix out on my fork and can verify it works on both iOS and Android. I was able to `identifyUser` and `updateUser` with custom attributes from our app. Chatting back and forth from Intercom to devices and emulators worked as well :shipit:

**Comment by ddomingues** [comment]
Hi @v3rm0n. Could you merge it?

**Comment by v3rm0n** [comment]
Released as `2.0.2`

**Comment by zanuka** [comment]
Using this package now in production apps and it's working perfectly, nice work!

**Pull request merged**
